### ISSUE TITLE
close() call does not seem to send data before closing

### ISSUE THREAD

**Issue by sashman** [brightcove/hot-shots#41]
Hey,

I have the following code: 
```
    const graph =new StatsD({ host: 'example.com', port: 8125})

    const responseTime = Date.now() - this.startTime
    graph.timing('.response_time', responseTime)

    graph.close(function(err) {
      console.error('The close did not work quite right: ', err)
    });
```

With the `close` call there, no data is sent out at all. Am I using it correctly? The docs specify all data should be sent before the socket is closed.

Tested with `tcpdump -n udp dst port 8125`

**Comment by bdeitte** [comment]
timing() is asynchronous.  There is a callback that you can add to it, that's optional, that returns when the data has really been sent.  If within that callback you called closed, I would expect you see the data sent.  If that's not the case, please feel free to reopen!

**Comment by bdeitte** [comment]
Yes, I see there is a bug here.  Thanks for catching this!  I am not able to find the time to fix this myself, but I am happy to accept a PR from anybody who does fix this and will keep open this issue.

What needs to happen here is that the flushQueue callback can't be ignored:
https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L526
The callback for flushQueue needs to be listened to within close() before moving on with anything.

**Comment by guyisra** [comment]
@bdeitte You mean it should be 
`this.flushQueue( () => this.socket.close())` ?

**Comment by bdeitte** [comment]
@guyisra Something like that, yes.  socket.close() can thrown an error so the existing catch call needs to be in there.  Also this library isn't currently using babel and has never formally deprecated any version of Node, so we'd have to do a major version bump to use the now-usual ES6 goodness.

**Comment by guyisra** [comment]
From what I see is that when close() is called, the buffer is empty and the socket closes immediatly. But then the message that was sent (before the close()) is trying to get out but the socket is already closed. It would seem that the messages that need to be sent should be enqueued (or I probably misunderstand the intent of enqueue() so when the socket gets closed, it will go over the bufferHolder and finish the enqueued message before closing. Does this make sense?

**Comment by bdeitte** [comment]
I think what I propose above would solve this, and you don't need any other enqueued message solution.  The buffer can be empty but the message can still not be sent- in order to know this you have to listen to the socket callback: https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L502

This socket callback is in the end what's listen to when you add a callback listener for flushQueue().  You then can be assured all of these messages are sent and really close the socket.

**Comment by guyisra** [comment]
When trying to put the close() as the callback of flushQueue() and trying to do `client.close()` after a call to `client.increment` it seems that flushQueue() doesn't have anything to flush, and continues off the closing the socket without waiting for the message to be sent. When the message gets around to be sent, it fails on the send since the socket is already closed

**Comment by bdeitte** [comment]
Oh I see.  So the flushQueue() solution will fix some cases but not all of them.  There's also the case you described which would be fixed by:
1) Within your code making sure the increment callback is used before calling close
2) A much better solution in the library which essentially takes care of this
I'm not sure offhand what the right solution is for the second one.  I mean, I can think of one (keep track of any outstanding callbacks in a global count) but I wonder what the best solution here is, don't have much time to think about it right now unfortunately!

**Comment by bdeitte** [comment]
Yes, still an issue.  If anybody wants to fix in the short term, please look at open PRs and build off of those, if there are any big ones.  I've been overhauling parts of the codebase, have another PR coming for that as well.

**Comment by bdeitte** [comment]
Happy New Year- fixed this up in the PR above if folks want to review it or try it out.
