### ISSUE TITLE
Support the new Unix Domain Socket transport

### ISSUE THREAD

**Issue by xvello** [brightcove/hot-shots#53]
The [Datadog Agent6](https://github.com/DataDog/datadog-agent) dogstatsd supports [submitting  metrics via a Unix Domain Socket](https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support) instead of UDP. This is very useful in container environments where network connectivity can be a hassle, and allows error detection.

[This wiki page](https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support) lists current implementations and a common testing methodology to validate client libraries.

If you need help with implementing the protocol, please don't hesitate to ping me!

**Comment by bdeitte** [comment]
Hi @xvello thanks for the heads up!  I maintain this project, and I am not going to have any time at all to try to implement this unfortunately.  We have a lot of people who have contributed here, so if anybody else wants to step in by all means please do.  I am always prompt and happy to review anything that comes in right away.

**Comment by voxxit** [comment]
I can see if I have some time in the next few days. Stay tuned.

**Comment by xvello** [comment]
@voxxit That's great news!

You can find the list of compatible libraries [in our documentation page](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/), if you want to benchmark existing implementations.

**Comment by bdeitte** [comment]
This should be a lot easier to do with some of the changes I've made in the last month, with the tests being revamped to be easier to add to.

**Comment by gabsn** [comment]
@bdeitte I actually need this feature since we use **hot-shots** to send metrics from our node app. Do you know what else remains to do to be compatible with UDS? (I also work at Datadog btw)

**Comment by bdeitte** [comment]
@gabsn Great!  So a new protocol should be added for this, similar to how 'tcp' was done at one point.  It's all in one file for changes to make, like here: https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L41

You'll also want to add some tests.  There's no real unit tests in here- these are all actual tests where we bring up and tear down the client/server over and over.  So to add your new protocol in the mix to all the tests, look at testTypes() and testProtocolTypes(): https://github.com/brightcove/hot-shots/blob/master/test/helpers/helpers.js#L51 And I would expect creating the server to change: https://github.com/brightcove/hot-shots/blob/master/test/helpers/helpers.js#L71 There have also been special cases added in places to the tests, depending on behavior.  So that will be something you can figure out if tests fail, although things generally just work here for the two existing protocols.  And if there's anything new that should now work, please add a test for that.

**Comment by gabsn** [comment]
Ok thanks, I'll let you know when the PR is ready!

**Comment by bdeitte** [comment]
See https://github.com/brightcove/hot-shots/pull/107 for the latest on this

**Comment by bdeitte** [comment]
Added in 6.3.0
