### ISSUE TITLE
Only messages sent via TCP have a `\n` delimiter appended

### ISSUE THREAD

**Issue by elliotwonghk01** [brightcove/hot-shots#99]
Any idea on why only messages sent via TCP have a `\n` delimiter appended?

https://github.com/brightcove/hot-shots/blob/90ba5837b35a4f77f0bf459ee846f9541942ac9a/lib/statsd.js#L321

**Comment by bdeitte** [comment]
Is this causing an issue for you?  Only tcp has this, because tcp was added second and I assume it was needed for some agent using this.

**Comment by elliotwonghk01** [comment]
Yeh we were using [socat](https://hub.docker.com/r/alpine/socat/) to monitor the published metrics, which identifies and splits metrics by `\n`. Without the delimiter, the metrics simply can't be separated.

**Comment by bdeitte** [comment]
Got it.   Have you considered then switching to TCP?  I don't see changing the default for UDP here, given it's been in place that way since the beginning and I have no idea no the effects of such a change on all statsd versions and flavors.  Alternatively, someone could add in an option to make this an optional thing that happens.

**Comment by bdeitte** [comment]
I don't expect this is something that we can change, unless you want to make it configurable.  Again if you want to do that in a PR, happy to look it over.  As it is for a bug, I'm going to close this out.  Thanks.
